// client-react-app/src/authenticationModule/components/AuthenticationPanel.js
import React, {useState} from 'react';
import './AuthenticationPanel.scss';
import 'react-bootstrap/dist/react-bootstrap'
import 'bootstrap/dist/css/bootstrap.min.css';
import {Button} from "react-bootstrap";
import authenticationUserView from 'authenticationModule/authenticationUserView';
import debounce from 'lodash/debounce'
import UserAccountForm from "./UserAccountForm";

 const AuthenticationPanel = (props) => {

    const [login, setLogin] = useState('');
    const [password, setPassword] = useState('');
    const [authenticationPanelView, setView] = useState(authenticationUserView.CreateUserInfoView);
    const [count, setCount] = useState(0);


    const renderRightPanelView = () => {
        switch (authenticationPanelView) {
            case authenticationUserView.CreateUserInfoView:
                return (
                    <>
                        <h1 className="mb-4">Załóż konto</h1>
                        <Button type="submit" className="btn btn-primary rounded-pill"
                            onClick={() => setView(authenticationUserView.CreateUserAccountView)}>Submit</Button>
                    </>
                );
            case authenticationUserView.CreateUserAccountView:
                return (
                    <>
                        <h1 className="mb-4">Użytkownik</h1>
                        <UserAccountForm click={data => {
                            props.createUser(data);
                            setView(authenticationUserView.AccountCreatedInfo);
                            const setUserInfoView = debounce(() => setView(authenticationUserView.CreateUserInfoView), 3000);
                            setUserInfoView();
                        }}>
                            <Button className="btn btn-primary rounded-pill" type="submit">Stworz uzytkownika</Button>
                        </UserAccountForm>
                    </>
                );
            case authenticationUserView.AccountCreatedInfo:
                return (
                    <>
                        <h1 className="mb-4">User created Seccesfully</h1>
                    </>
                );
        }
    };


   return(
       <div className="authentication-panel-container container-fluid">
            <div className="row d-flex authentication-panel">
                <div className="col authentication-panel authentication-panel__login-column--left">
                    <div className="w-75 d-flex justify-content-center flex-column">
                        <h1 className="mb-4">Logowanie</h1>
                        <div className="mb-4">
                            <input className="form-control" aria-describedby="emailHelp" placeholder="login/email"
                                   onChange={(event) => setLogin(event.target.value)} value={login}/>
                        </div>
                        <div className="mb-4">
                            <input type="password" className="form-control" placeholder="Password"
                                   onChange={(event) => setPassword(event.target.value)} value={password}/>
                        </div>
                        <Button type="submit" className="btn btn-primary rounded-pill" onClick={() => {
                            props.loginUser({login, password})
                        }} >Zaloguj</Button>
                    </div>
                </div>
                <div className="col authentication-panel authentication-panel__login-column--right d-flex justify-content-center flex-column">
                    {renderRightPanelView()}
                </div>
            </div>
       </div>
   )
 };

 export default AuthenticationPanel;

// PersonalManager/ClientApp/src/app/authentication-panel/authentication-panel.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {AuthenticationService} from '../services/authentication-service';
import {AuthenticateUserQuery} from '../services/models/authenticationModels';
import {Router} from '@angular/router';


export enum RightPanelViewEnum {
  CreateUserInfoView ,
  CreateUserAccountView ,
}


@Component({
  selector: 'app-authentication-panel',
  templateUrl: './authentication-panel.component.html',
  styleUrls: ['./authentication-panel.component.scss']
})
export class AuthenticationPanelComponent implements OnInit {
  private authenticationService: AuthenticationService;
  private router: Router;
  public login: string;
  public password: string;
  public showNotification: boolean;
  public rightLoginPanelView: RightPanelViewEnum;

  constructor(authenticationService: AuthenticationService, router: Router) {
    this.showNotification = false;
    this.authenticationService = authenticationService;
    this.rightLoginPanelView = RightPanelViewEnum.CreateUserInfoView;
    this.router = router;
  }

  ngOnInit(): void {
  }

  loginChange(value) {
    this.login = value;
  }

  passwordChange(value) {
    this.password = value;
  }

  async onLoginClick() {

    if(!this.login || !this.password){
      return;
    }
    const query = new AuthenticateUserQuery(this.login, this.password);
    const result = await this.authenticationService.authenticate(query).toPromise();
    if(result){
      await this.router.navigateByUrl('/test');
    }
  }

  onCreateAccountButtonClick() {
    this.rightLoginPanelView = RightPanelViewEnum.CreateUserAccountView
  }
}



<div class="authentication-container container-fluid">
  <div class="row d-flex authentication-panel ">
    <div class="col authentication-panel authentication-panel__login-column--left">
      <div class="w-75 d-flex justify-content-center flex-column">
        <h1 class="mb-4">Logowanie</h1>
        <div class="mb-4">
          <input class="form-control" aria-describedby="emailHelp" placeholder="login/email"
               [(ngModel)]="login" (ngModelChange)="loginChange($event)">
        </div>
        <div class="mb-4">
          <input type="password" class="form-control" placeholder="Password"
               [(ngModel)]="password" (ngModelChange)="passwordChange($event)">
        </div>
        <button type="submit" class="btn btn-primary rounded-pill" (click)="onLoginClick()" >Zaloguj</button>
        <div [hidden]="!showNotification" class="form-text">Niepoprawne dane użytkownika(sprawdź login i hasło)</div>
      </div>
    </div>
    <div class="col authentication-panel authentication-panel__login-column--right d-flex justify-content-center flex-column"
            [ngSwitch]="rightLoginPanelView">
      <ng-container *ngSwitchCase="0">
        <h1 class="mb-4">Załóż konto</h1>
        <button type="submit" class="btn btn-primary rounded-pill"  (click)="onCreateAccountButtonClick()">Submit</button>
      </ng-container>
      <ng-container *ngSwitchCase="1">
        <h1 class="mb-4">Użytkownik</h1>
        <button type="submit" class="btn btn-primary rounded-pill" routerLink="/test" >Submit</button>
      </ng-container>
    </div>
  </div>
</div>
